[package]
name = "creational"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "singleton"
path = "src/singleton.rs"

[[bin]]
name = "sconfig"
path = "src/sConfig.rs"

[[bin]]
name = "logger"
path = "src/logger.rs"

[[bin]]
name = "docfactory"
path = "src/factory.rs"

[dependencies]
