[package]
name = "waytoodeep"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
tokio = { version = "1.9.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
