[package]
name = "basics"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "enum"
path = "src/enum.rs"
[[bin]]
name = "struct"
path = "src/struct.rs"
[[bin]]
name = "vec"
path = "src/vector.rs"
[[bin]]
name = "hash"
path = "src/hashmap.rs"
