[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
metaplex_nft = "BJ4WxMKh29S3tNZcA3SwpYfjJJ32vSqB8db1qpFdWmT8"

[programs.devnet]
metaplex_nft = "BJ4WxMKh29S3tNZcA3SwpYfjJJ32vSqB8db1qpFdWmT8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://polished-warmhearted-frog.solana-devnet.quiknode.pro/9bc0c3437243817577c59c3690d3bcde03fe8b6f"
wallet = "~/.config/solana/turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
