[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.30.1"

[programs.localnet]
counter = "nLjxYLhw8eSjrG4ui8rZvCZR44tmpb9PRBqtQ36MmhR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/aquental/.config/solana/calyptus-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
